Draft: Feat/promotions docs
Prisjakt/feed-specification pull request #62
Opened 2023-12-12 15:04 UTC by pj-sp

2023-12-14 09:14 UTC, andrejohansson commented
General structure change:

![image](https://github.com/Prisjakt/feed-specification/assets/2828428/18955210-532b-4eb5-9969-75b44fb68cf7)

2023-12-14 09:26 UTC, andrejohansson requested changes
Nice work, some things to adjust then we are good to go!

2023-12-14 09:26 UTC, andrejohansson commented on docs/fields/index.md
> +- Product feeds
This is good, but perhaps we can clarify target audience a bit:

- Offer feeds (used by shops)
- Promotion feeds (used by shops)
- Product feeds (used by manufacturers)

2023-12-14 09:26 UTC, andrejohansson commented on docusaurus.config.js
> +          }
Isn´t the code above doing the opposite of the comment?

2023-12-14 09:26 UTC, andrejohansson commented on docs/examples/_xml_promotion-min-sample.mdx
> +<rss xmlns:pj="https://schema.prisjakt.nu/ns/1.0" xmlns:g="http://base.google.com/ns/1.0" version="3.0">
Prisjakt namespace should not be the same as for offers.
We should add a new [namespace definition](https://github.com/Prisjakt/feed-specification/tree/master/static/ns) in this folder and reference it.

2023-12-14 09:26 UTC, andrejohansson commented on docs/examples/_xml_promotion-sample.mdx
> +<rss xmlns:pj="https://schema.prisjakt.nu/ns/1.0" xmlns:g="http://base.google.com/ns/1.0" version="3.0">
Prisjakt namespace should not be the same as for offers.
We should add a new [namespace definition](https://github.com/Prisjakt/feed-specification/tree/master/static/ns) in this folder and reference it.

2023-12-14 09:26 UTC, andrejohansson commented on docs/examples/_xml_promotion-min-sample.mdx
> +    <title>Prisjakt Minimal Example Feed</title>
Prisjakt Minimal Promotions Feed

2023-12-14 09:26 UTC, andrejohansson commented on docs/examples/_xml_promotion-min-sample.mdx
> +    <description>This is an example feed with the minimal values required</description>
Minimal values for promotions

2023-12-14 09:26 UTC, andrejohansson commented on docs/examples/_xml_promotion-sample.mdx
> +    <title>Prisjakt Example Feed</title>
Prisjakt Example Promotions Feed

2023-12-14 09:26 UTC, andrejohansson commented on docs/examples/_xml_promotion-sample.mdx
> +    <description>This is an example feed with the minimal required and all accepted values</description>
promotions feed + remove minimal

2023-12-14 09:26 UTC, andrejohansson commented on docs/fields/promotion/coupon_value_type.md
> +<RequiredField/>
This field is not required.

2023-12-14 09:26 UTC, andrejohansson commented on docs/fields/promotion/promotion_effective_dates.md
> +
We should add a do/dont section or update validation rules to explain logic regarding dates. Such as "you cannot edit a started promotion", "you cannot remove passed promotions" etc. Depends on the business logic in BC.

2023-12-14 09:26 UTC, andrejohansson commented on docs/terminology/prisjakt-specific-fields.md
We should have three sub headings here "offers, promotions, products" and explain what fields we have extended with.

2023-12-18 22:48 UTC, pj-sp commented on docs/fields/index.md
> +- Product feeds
done

2023-12-18 22:48 UTC, pj-sp commented on docusaurus.config.js
> +          }
added a description in a comment

2023-12-18 22:49 UTC, pj-sp commented on docs/fields/promotion/promotion_effective_dates.md
> +
added

2023-12-18 22:49 UTC, pj-sp commented on docs/terminology/prisjakt-specific-fields.md
done

2023-12-19 08:30 UTC, pj-sp commented on docs/examples/_xml_promotion-sample.mdx
> +<rss xmlns:pj="https://schema.prisjakt.nu/ns/1.0" xmlns:g="http://base.google.com/ns/1.0" version="3.0">
done

2023-12-19 08:30 UTC, pj-sp commented on docs/examples/_xml_promotion-min-sample.mdx
> +    <title>Prisjakt Minimal Example Feed</title>
done

2023-12-19 08:31 UTC, pj-sp commented on docs/examples/_xml_promotion-sample.mdx
> +    <description>This is an example feed with the minimal required and all accepted values</description>
done

2023-12-19 10:00 UTC, andrejohansson approved these changes

2023-12-20 07:42 UTC, merged